### ISSUE TITLE
Add support for including XML files within ffxml files

### ISSUE THREAD

**Issue by jchodera** [open-forcefield-group/openforcefield#19]
This feature was just added to OpenMM: https://github.com/pandegroup/openmm/pull/1785

**Comment by davidlmobley** [comment]
What's the use case, @jchodera ?

**Comment by jchodera** [comment]
I primarily don't want the behavior of the OpenMM and openforcefield `ForceField` to get too out of sync, but there may be benefits to having properties split out into different XML files. For example, one could imagine a all-atom and united-atom versions of the forcefield that differ only in the `<NonbondedForce>` tag that import the same valence terms from a single file. Or you might want to optimize only one force term for an experiment (e.g. `<NonbondedForce>`) which is included from a different file since it changes each iteration.

**Comment by davidlmobley** [comment]
OK. So you basically want us to propagate the type of changes that were done in the issue referenced above into this code?

**Comment by jchodera** [comment]
I think that would be useful, yes. It doesn't have to happen immediately, but it would be useful to do eventually.

**Comment by davidlmobley** [comment]
One challenge here will be to figure out where to insert the included XML lines within the existing XML, since this is a hierarchical format. The easy answer is "where you included it", but I think this is incorrect since the XML file would presumably be included in only one place (at least, for conciseness that would be nice) but its parameters might belong in multiple places. I'm thinking of water, for example, where we would have constraints, charges (?) and LJ parameters that would have to end up in the right places. Oh, and bonds/angle.

**Comment by jchodera** [comment]
That's a good point. We may not actually want/need that capability as a result.

**Comment by davidlmobley** [comment]
Well, as you noted in #26, we can deal with this by making sure the SMIRKS patterns in included FFXML files for water ONLY match water. But in general this would be dangerous.

**Comment by jchodera** [comment]
We would likely want to use an XML include tag to include a water model like TIP3P since we would want to mix-and-match for testing purposes.

**Comment by davidlmobley** [comment]
Yes, I absolutely agree. Making it painful to swap water models would be a horrible thing for building a user base. :)

**Comment by jchodera** [comment]
Closing this for now. We can reopen it if we find we actually need it.
