### ISSUE TITLE
Loading forcefield from ffxml in openforcefield/data/forcefield fails

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/openforcefield#22]
I've tried to use the following script lines:

```
from openforcefield.typing.engines.smirnoff import forcefield
ff = forcefield.ForceField('forcefield/Frosst_AlkEtOH.ffxml')
```

This gets the following error:
```
OSError: Error reading file '/Users/bannanc/anaconda3/lib/python3.6/site-packages/openforcefield/typing/engines/smirnoff/data/forcefield/Frosst_AlkEtOH.ffxml': failed to load external entity "/Users/bannanc/anaconda3/lib/python3.6/site-packages/openforcefield/typing/engines/smirnoff/data/forcefield/Frosst_AlkEtOH.ffxml"
```

There is this [#TODO](https://github.com/open-forcefield-group/openforcefield/blob/master/openforcefield/typing/engines/smirnoff/forcefield.py#L561) in the loadFiles method in forcefield.py

It seems like this would be fixed by using the get_data_filename. If that works I'll put in a pull request today.

**Comment by davidlmobley** [comment]
I'm not sure this qualifies as a bug, but yes, you need `get_data_filename` if you want to specify a relative path.

**Comment by davidlmobley** [comment]
Resolved by #23

**Comment by jchodera** [comment]
OpenMM recently added a way in which other conda packages could register their install paths with `ForceField` so that these directories would be searched too. We should probably add this capability so that, for example, the forcefield packages we deliver can be separate packages from the openforcefield toolkit.

https://github.com/pandegroup/openmm/pull/1789

**Comment by davidlmobley** [comment]
Ooh, cool.
