### ISSUE TITLE
For consistency change AlkEtOH to AlkEthOH

### ISSUE THREAD

**Issue by bannanc** [open-forcefield-group/openforcefield#36]
We are not consistent in file names or references to the Alkanes, Ethers, and Alcohol sets. Some say `AlkEtOH` and others `AlkEthOH`. I like `AlkEthOH`, it is also what I think most of us have been saying out load when we talk about the set. Not a big deal, but we should probably be consistent before we publish the smirnoff or smarty papers.

**Comment by andrrizzi** [comment]
Sorry to jump in with a vaguely related topic, but I've also noticed that some of the force field files use `SMIRFF` as a root tag, and some use `SMIRNOFF`. Not sure if this is intended, or if there's still time to standardize it.

**Comment by bannanc** [comment]
Thanks @andrrizzi I think my most recent PR fixes all of those. I spent a fair amount of time searching for smirff and SMIRKS Force Field in the Repo yesterday.

**Comment by bannanc** [comment]
Currently forcefield.py supports both `SMIRFF` and `SMIRNOFF` since we had a name change, but the intention is to move away from `SMIRFF`.

**Comment by andrrizzi** [comment]
> Thanks @andrrizzi I think my most recent PR fixes all of those.

Oh, sorry! I didn't notice.

**Comment by davidlmobley** [comment]
@andrrizzi - Yes. SMIRFF was what it used to be called but, er, one outspoken member of the collaboration does not like small blue cartoon characters apparently. I'm already starting to form a talk slide involving SMIRFF-bashing out of this. :) So, we're in the progress of switching everything.

@bannanc - My preference is for AlkEthOH rather than AlkEtOH and this has been bothering me for a long time, but I've always been too lazy to fix it (the inconsistency dates back to when the repos were very first created and Chris called things one name and John used the other....).

**Comment by bannanc** [comment]
@jchodera or @cbayly13 do you have a strong preference?

**Comment by davidlmobley** [comment]
@bannanc - I don't think @cbayly13 gets GitHub notifications at high priority so if you want to ask him, you should ask on Slack or by e-mail (even by sending a link to this issue).

**Comment by jchodera** [comment]
I prefer AlkEthOH as well!

**Comment by bannanc** [comment]
I'm working on finding all the `AlkEtOH`s in PR #40
